function parseText(inputText) {
    // Разбиваем текст на 32 буквы - слоги
    const slogs = inputText.match(/.{1,32}/g) || [];

    // Индексы символов, которые нужно оставить
    const indicesToKeep = [5, 3, 8, 7, 6, 11, 9, 2, 21, 19, 24, 23, 22, 27, 25, 18];

    let result = '';
    slogs.forEach(slog => {
        // Для каждого слога, делаем фильтрацию по индексам
        indicesToKeep.forEach(index => {
            if (index < slog.length) {
                result += slog[index];
            }
        });
    });

    return result;
}

function countSlogs(text) {
    // Разбиваем слоги на другие на слоги, состоящие из 2 символов
    const slogs = text.match(/.{1,2}/g) || [];

    // Создаем объект для хранения количества слогов
    const slogCount = {};

    // Подсчитываем количество каждого слога
    slogs.forEach(slog => {
        // Приводим слог к верхнему регистру для учета регистра
        const upperSlog = slog.toUpperCase();
        if (slogCount[upperSlog]) {
            slogCount[upperSlog]++;
        } else {
            slogCount[upperSlog] = 1;
        }
    });

    return slogCount;
}

function replaceSlogs(text) {
    const replacementMap = {
      'KI': 'о',
      'NO': 'к',
      'OO': 'у',
      'HH': 'п',
      'NA': 'а',
      'PC': 'ц',
      'OI': 'и',
      'CD': '1',
      'MB': '-',
      "OE": "В",//4,
      "AA": " ",//306,
      "CK": "х",//19,
      "ON": "д",//49,
      "ME": "е",//166,
      "EO": "ш",//13,
      "FG": "т",//86,
      "CH": "р",//128,
      "DH": "м",//73,
      "DP": "л",//85,
      "AJ": "н",//131,
      "FA": "з",//17,
      "DD": "г",//35,
      "HF": "в",//102,
      "BN": "ж",//13,
      "MC": "с",//94,
      "IE": "й",//36,
      "KC": "ч",//11,
      "EB": "я",//46,
      "FM": "ы",//20,
      "FN": "ь",//20,
      "NG": ".",//25,
      "FH": "Н",//2,
      "LD": "-",//8,
      "AH": "У",//2,
      "HP": "5",//1,
      "DC": "Х",//1,
      "EJ": ",",//24,
      "GP": "А",//6,
      "BM": "С",//10,
      "JK": "К",//5,
      "HD": "Д",//6,
      "FI": "ё",//3,
      "DE": "щ",//6,
      "JP": "ю",//5,
      "CF": "Ш",//1,
      "KK": "б",//19,
      "AL": "П",//5,
      "GB": ":",//1,
      "BE": "“",//3,
      "BP": "М",//3,
      "BG": "„",//3,
      "CI": "Г",//3,
      "NF": "з",//1,
      "PO": "2",//4,
      "CC": "ф",//7,
      "FJ": "Э",//2,
      "IH": "э",//6,
      "PF": "Т",//1,
      "OK": "О",//2,
      "MF": "Ц",//1,
      "AG": "3",//2,
      "DJ": "Р",//3,
      "FC": "[",//1,
      "BK": "4",//3,
      "MH": "]",//1,
      "DL": "Ф",//2,
      "BO": "Й",//2,
      "HG": "7",//1,
      "ML": "(",//1,
      "CE": ")",//1,
      "HL": "И",//1,
      "JA": "0",//1,
      "LA": "8",//1,
      "MB": " ",//1
      "NH": 'Б',
    };
  
    // Разбиваем текст на слоги по 2 символа
    const slogs = text.match(/.{1,2}/g) || [];
  
    let result = '';
    for (const slog of slogs) {
      // Проверяем наличие слога в алфавите
      const replacement = replacementMap[slog.toUpperCase()];
      if (replacement) {
        result += replacement;
      } else {
        // Случай, когда слоги не найдены в алфавите
        result += slog;
      }
    }
  
    return result;
  }
  

// Этой функцией мы выводим на экран информацию с суммой всех слогов
function displayObject(obj) {
  const pre = document.createElement('pre'); // <pre> для форматирования
  pre.textContent = JSON.stringify(obj, null, 2); // преобразуем в JSON и устанавливаем в textContent
  document.body.appendChild(pre);
}

const inputText = "DPIEJOCAAKAKECKOEGONJOAEMEAAAPJAEFHGCFCOODFHCKHADIEABNNAAMFHEHICHKJHJCOPDAFIHHJAMKAAPNOAAABIBABANNDHKCFANDJAFFCIJNAHDCDIKNOHBIIBFIAAPACFHNDHEMNEOCONEBMEMNBCDCOIIBDILKAEIDFAIPCFHNHHDCHOOHKHKOKKDDFIAOKHCHKILBIFGKFOENAIOHLACHOOGGAENMDHCNJHFIHJNFHKNCAGFHMAOPFMODGHACNANFHOBIHIPLCIJOMCKMDEPDKDKNHOKNAIOHDAOIPJDAHIAKMGFCCEKKKBOJCBAEAPDMGAEACMOGAIBOFPDAFMIHADEOANPOEPDACBPKEODNNNIODANFKPGCHHBDOJCAIEMEIEJNALDBAECMKDDAHIIFOJFHHCPMHIKCJHBMLJCNFIPKOGFHHICFLDGBIPKDAEMOHJEPBNAAHBKEAGNFPAFDMCPHCEEMMHDPGENCHNELAOINMIKAGEGHIOCLAOCNDIKNOHGPNBNJFJGAKNOHEIDAPEEIEABNOJAMCIFLINJPIAAACHHOPHGMOBGLAJEADIONMHDNMEFLFPPDAIKHJADACLNLHCBMAEMDAADCECOAAEOMFHCAPMKBKCJFANDOEPDANBACOPCPIOMNHANOIHDEONEEBGDFDOOEFPBANBIIACKPOIOAMIKJDECGICFMKFHOOIAOPDKMHKBCDAACGDKFEDMHIOEOHHHOCHMMCMCMIHFCHIKKLFPMHHCNEOFNHAAMIHNLEGJJAHICOEMAINIKLKEEPADNDJADEDKPKNBNHIOKNDLDKACDJCEGOEAMOHCNIIGNEGBHOAHNMJANJCABJAFLAIKOOHDAKIGHJFADCFPHIIKMAEJAMPKBIONNDANOFHFHCFAHNGBNAAABAHHNIGMLAEGMHAAAJPDCBBFMAHODEANAOBKNGFNJOHGHMHCNGEDNCMAFIHFCFANOMGDJGHEFCPFDAIOMIANFHPFKIIMKCHHKGHKNEACKPGHFHIODFFNPNNBOEEAMOJAMCIOKBCCEHADAMJADPEMEFEEEIEIMNCPOEOPODHOPIEFMMAAKECAGFOPJJEGMONOALIFFDJEGBEKMOJAEFIDOPEMKCAHAAFHDEAOFHBOMAIJKHHCNKFEFBABAJGEFOIOEKINKNNMFCAJAHPGMDFMILDANIGLFOHCOLIKCGKEBAJCENAANGHEFCDBHIFMHCANOJHJAEDLPMIHOAGNBOAEOMEPCOGDFHANNLFCFEGCMGACNJAANJKEFOBDJJAAAFDHABIFMOCFHAIPONCPAJANPAFOCCFJHECMKJBPCOMGNIEDMNCMODOEHNOEMIAAAKHHKMIJGEMNMPEADEHCDJBFIIBNCIAKNNAAKLOHPBOFMNHEDAANOOJJNBHHCIOFODPJOJEKANCPEAKGCOAAAFIJKEFJDAOANDIKNDHPHOMFNHJCAONOCAIKNFKHIAIFKEFHAJJMHMEHKECIMCGFMIHCEPGEOOHPDHIOEBFCNPHEDBIGOMKCEKCLJNGKAFAKAFIKHIGPLJBPKIEDMFCMOKGOBOCBDIAFAHCMKJFPMNNHBIIMOHAAKDFIDKBOPAEAINCMNDOHAPBMCHAIAAFHCEAMFIKNBJAONKEIAIIELINKKFABAFIKHGGLHDBHDGEAMMGFFBCDMHCOJJFJHAEMABJDIHAMGIIFKFCMODGFICFOMPAPACMBGNFPNIKEEEAIAAIOOFAJCEPADOEBMOPDNLIPCMIKBIILKCKKOIHOFHCGHIGEFAANOPJHJLMBDLINOAGNAHAMMKOGJCHHCOEMMNNEAIBPHIGMFHANOEFHBGFLEIGMFDEMOJPJAGGECCAIAFFHMOMDABBIHIOMEDEMKJDMMLAPJHAPAMJADIEHEDEDJIEPMNCPKOOCCOFNFODGDAIKNGAOGMCLNJIHKNHDACAPHAFFFANDOHIKNBFOEPJOAAJOAEIOAABPFBMDCFABFEANHMBCIFNOLIPPDDBEOFPHKHAADPBAGBAABHEIJANEBIMMFOAAKNNHAPGDNMPLDANBFCJAHEIIANALANHCOJAPAIGMEGIPKNFHFLAPGPMEBANOFECMAGBEHLGMANOENBANOFNBDDHGMFIDKAEIHKACKDCIPIIMKDAFKHHHNBBCMCNHBKJAMCIBHFMDCIGMFAIOKFAIDHAAIHOFNOONHGOFDEBJDIACNOCPOEICJHMIEOABANJAEGAOEEODAGEHMAEIFDABIJEFIIEPMCHCOHHFHNALHIGHFCIKOOHCJHHCEHIKONAADGAFHEJHMOEMMOHCNOIGBALEEOAANMJANKCPBJFBDJIBOOHDELIDJJAHEJAJAAANAAABAPHKAOEOMCAAONHNGPPPPICJMNCMOFOJOBAPOFHMDAIOHOAJBBABDAIIKAIONCJIBAAFKGHPDBIONCGLBIBFHEADAKEOIHICBHNNBJCAMNONEBAMFPDIECALANHCMGAJALJEIIHFHDIKKDPFAEDFPJNOBAEMAOJGAANIBFMEFAEMHEABDEOAFPACAKICDIIELCKPMNPHDAANOFJGDKFEGAIJOEIOAIJAEKKFKEMOBHEMMEFDCPGDBFHPCLIKNJDMFOMCPNAMNNHHOOAGMCHIDAJFAIIKAIELBONIMHIBCCEMDJHKPMEAEIAJNOJAONIKOCBPLDADAAIOHMAAIFNKPIAJNOJAOHIENACDAAJJENAANAONCICHKOHNHFIOOCGHKPHMNIPHDCIOKNHEPJEHGIFMHDANOKPFDONGMHAIAMHHCDEJBPHOOOEPMANOPKANHKLLBADPCIDLAMEGNHMIIGKLKOHCFDIGEGHHCOAMNMJANLCKAFMBBDIFKAEIDPAGAGHMAHHNCHOOHIHPMIGACAINKAEINFAMDDHPOEHJCOHDIDIPDCBJCPAMAMCCDHEHNFCICANOFDNONLHMJEGBJPHFCNOEDHAHFJCAMGANNNAANDHBHMKNJJAFAKPBAHIPNILOMHGPFKDDDKIBKKKPHGEBMOHCNIINMKJHOEACACLAMOHCBGEKHGOKNNHCFNAAPMCAHCICOAPDMGACNACGHIIAKCHHKAHNLDLGCPGIFHIODJFKEMKCHEEIMOJAMGIPEGKAODADAAIODBAIMGBFLAEPMDHCNDHJCCPLIIJHANCMOEOGJNNPOIEJIHAAKMFJKDLOJIEJMAJAKKJAOEGDNHDMLKHDCBINHDBCGECKMKONILIAMGGJHIAMADCCKDPMABNFAAGNFAAANBJAONGMLPAFANHNDJADEJCGECGBFIIOMLEDMBHHEAODNDIKADHOHDILDEIDOBAAMFMLDEIBNJFGHCEMAKHFFABEOHIIKAHDDJAMMNEJOKIMKEHCCEBJMLAOFIJBEAAAKEJEAOCLHOAPAOPDEOIIJGEKCHNNFHAACCHKIPHFGFIEKOGFHFICDANJMDAAAAANDFJPEJEEIAPPDLIKNADFPOIONIHODCEMOOHEFHJEHCOFNAANMNJCCJHDDAOHNCIOADKCCPJGDGCIMDIONMPHBLGBMCAFAMHFMJEIPNPNIHHADFIKCGGOFOFEJABKEAAANMJPCGHPHHAJANAFHOABEKKMDAHKCFEMAAGJBANLDEJFFFEIMEAPICDEMOJJANKCONAHEALDKJHCINHCECAFFGBBFJAAAKPBAAIPDNGEAHGGFKDDDHIPCOFNBAEEMOHCAMIHGPDKPHHBCFANCAAPDBILNPEFMOOEDFINPABHGHJCEHAACGHDCIGJOAABNOFHNMNIJOCCIIALAMJAKAEGFKHNEICNCPIOOECDGHMLDJAFNFPDALNDPMEAOJIFKAJEACABBMICHOEFMNAFNAAFNHFBJOIMKAJAOGJPNHCBMFPAJIAAHNHEGKFHHAACNOONNMOPIHCNHACKPJIOAMPDGCIJBCJDADEMPMHAIJEAICEDMAFHMAABAFMMKCAIAKFHMMICNNEBFJGNFKIKAOCHFJBKIAIHKKDDAHILIIGAEJCKCKHCADIKPGNEEAGGFNANAHGBANFHLJFCPNANEMOHPDIMPHACAMJADCEMDCBNFIENMNCPOFOPKDBFNIEHMNAAKLOCJJAOIPHPCKANDNKBONOGMHIDOHAACMHGFMEHGPIPKKNODDIIACCDJINABDANOAPIKBOMIAAHAHHINMFGBKFLICOPNNOOPJAKBBCLIFIJOAPJHKANNMHEGOIKKMEINPCEMEBHNAACAFIOAEAOICLPEPKBJCOODFHIHJPHEIBBEOJAOENFOEPLBAICOOAAADINCMBBPGENOMIKFOCGPLDKLIIDKACKKGJCKFNLPHECIAAACPLPGHCCBIOBOMCMONCGODCFGDINOAGNHPADBABCBOPHDABEOGAIBLKDNHCDMKONCFINAMFHCBEMMOJAEOICJAPDNAABAHHINDFFLJAHCCOANNOOPGABIKHGJKIDOAIOKOADFJDJLAMBFOPDAPIAJDPKIFHBHOHCHIIMGGNLDEPHDKEMMGCHADCENIJDAAMFOJAKHPJJJAACAPDCAKOPKEAOFIHPIDCMOEHHDGHMJFJFAMCPHNECBPAMGAAPAFIOAOAHBCLHPIDBHAANOBJGEOFBGKIOOAGNOIADCOBCKICKMKIKKIKOMJBHHJEIMHAAAAFHLDEMOJICONHDAFAJKCBOHHIEOAEMHCAMPONCDIHFCHANOGFLEHILKNGJFDEMFMPHEDJNBICGMHGFKJFFMCIILJABAFDHABIJMNCBNAINONCPANAFPLMCDPOLOMNODLEDJLCIOABFEKPDAGIIKMHIHIIKKHGFKEFDPGDDNINCOAOOOKAFBHJHLIAHFHDLKEHGICLCONNLOOAAOEOJDEKBCFANNKHCHAIFCCPLPAAMACKJNNHDFJPDLECPMKJAIFIGKOOOEHAOACANDNHFBHDPKFIBOAIOHEABDMFAEOINKMEINOCFBKCKKOAHACDDOGHFKIGBCAHFHAHHNKAHJLAGKEHKCOHDIHILMAJCJEAFAMEBMLFAMKLLOGJGACGFBOHJBJIAJEANAAIOBJAMMPDOHGPOGMFHFMCDFOFEEGHPCEIOBIBMBCIPJKJBEKAAKHIPAOPFHAENDMEMAAEIKKDDNAOBNDIKNEHFJJDAEFJAAKNOHBIAOKFPEEAHNOJAMAIKCEAIIGAKAKONFHIEDBMDLHILKFHCDNMFCFCDBEILOFAAMBGIBEGMPNHHHCEMFKHJJJEFEOANAMIKOKCCBBIDMGEMDMEMFACBDLJJPPFHHEPDDHBHMEJHCPAMAMCCDEECGNNPLANEFDNONKHHBPGFEPHMCNOEDEAJDGEGDAABANPGAHGPMPABECKCJMEMMCCMLMEFLHEMMFPDCJNDCABNNGIGODJANIDGEFKMBHAPAAGADEAHAOPFNFAKNABEHNAOCDMNHEAOAMJDIDEPMCKGLAHIDECMAIJKBGGHFADHDMNOAKENOKLOLIJNACANKIKAMDPELCNOODIOMEPCOMNDKGBLEEAAFPOOHHJFFDAENAKKDAAMDKHGJHENMMJACDEMMDHDLAAMNNPDAOAFIPEAFEJJFFEIMNAEBLJIEOJEANKCOFAMMOBGPJHNINHCEMAAFPBIPPAKAFKKDBMGIFOMOGAFNKAAFJIBCDEEEFHMHNHCHGAFIGKLFAPFDAEMNHJPNGBIKHABAMJADEEKJDJHGAENMNCPNFOIMOJKKIBLEFAAKCCJDCBFIJDEDMJAAEEBGNKLAAJCAMMFAFEPHHFJOECDMCGFMEHNMFPKKLPJDAMFAPAHDEKDJJELMOHCAAOPAEIEBKAINAJEBHAOJPBAGADPCBDCACKHIPEJDAIHKOJAACIACIGJFAOINNANACOMCIFMKGOHNAIKFAJBJFDADNHKCDIKFAPCBNKFEAJOAIMFANEGBDHMCHFBHHIKCDHDMMGOOAICKECMAAJPAOALPJJHAAIKADADIKKMOAENMFAANJGOMDADCAOINMIOACEKPFEIOBHNCFANEGAJDBAJGHECDMIOMDEIHECLHEAJAKFHMLIPCKBFIBJMANJAEFALOILDHPACAMNODGEAEHCLFCEPMNDDPLAPGHDFCFIKOABEHGAHFMFJFPIBKDAADGDDDAFCAAALNMFHAMELKDLAKNCKMNAAOMAJHILEHAHIDCIONEHMBEFEKAPBDDIKAHHLFFNADLIBCAGNDLAPHFDNLEHPCOIOMONAEGGGHDKBKCOODGHPHHBFDAIDKEHDAJJPHECPNGHHHMIKFHCCBLHABFACNOFHHPIGMMHCKAOHEEANAPBNPANBEHFFHHIKCBHAMKHIEIINKACMKDACHHMABHAAANONHEAFJDPCLPILOOGFDMOHJAPAKIBDEOCPOLICCNNFNEAEAKIKMFKONLJCJDIMOAKCDBACEEOHAHHACHOOHOHAALKJHHACAMJADFEFCJDKEIEHMNCPOEOGKKKAMHKACNAACAABPOJPAAHGDIIOABEKEEFLHEHCHCEMMDHBILDGIHNBONAADEALCGHEOOEIMOHCNNIIOPDJDOAHNMJANACEKJBNOAIEOOHDANIENMCNACFPHIIKMMENHBFELIODNDANOIHJOJHFFNGDNOAAOIKHEFODIIJIANANKGOMIBFJLPADAKCMJOIDMECGMEAFFKJAMFIKONEFDHAMAKONDLIPALHKLIAFNOJAKHNDIGFAHIFPHAANOGJMDKLGHIEBMHAAKFHACNFMIKGHFMHCKKEMFBGEBPIJKNFHDIAACLDLFEIJKKAAMMKHPMBKGIABFDIKKDDAIGIHJIFHHCIKKGHFANPLHACKKKJAAEIIOAFIEIOFNHANOBHAHIMDIIGAFDOOOJPKPDLLMAHCCHIKNFFGMANMMAGPFENFACJCPBMAJIFBHFAAKHGHCKHAHIHNDKAAOKCMJCIIAACOMMPDADEDCMFLMAIHOAAANPJKAKLGOFAEAKCMHCINMGAJNOEHMMGFNLCOFBBJOEIMKDDLMJDJPGGHDJHMCNHDAKAPONFBFHCAMKONDEIAOEGBDIACACCCKDHAMLMPGJJEAMGFEOEDPFOCLIAFACHHOFHKEBCLFACDKDEMACHAFEOCOHDMDCEMDDHJHDLLLOAJNMJANACKLHMFLFIOOAEMHIAABDEEHOIBKMEINFCDOIEFJEAENHAAMBFDNEMBDAAHFMNOAIEMNMJJANNMODIKBOPLNKCCIKJMAAMFKGALBNKHOAMMFOPDACIEFJHLLAICKFCMNMGJEKNDGNFEHFANFBGCBJHOGJCEMABEAPAAJDBHFIABNOAAKENHOACHODCHMOGFDFIJMOCHOMJPAFOOFDGIHFMFKOKCCCAAOAHDCKKEHAKBKBEMNANIKEMJDLKHCAGNAMAMCLCHMFICKEJAHCBHLLDDKFACAMJAHLEKMJCABIIKKDAFKLHMAOBCDCNFBKJAMMICCCBAANGLFANFOKALJAADLJAHNFPDAINGGLHDMEEDMEEIMMOKHPDADADBDAIKFKAEDPHADDAJNEGFDPBBPIGLNJIDONFHANAPPEPDFHIPOABEHFANEHMJIDEIMMHCDEEBPFHMNHIJKKFHCAIKCKHAJAILKEFHAEJDOJMJCDKIJAGNHLACCNGIECIMFOJAPKIKFJFKIHAHANJAHNAMOEAEOIHGCHANOAFFDEOAEAPADHAAABFMNHMKGHJHDIEMDBEEIEOCAACFMAAANIJDGJCMPNCJKDANFOPMNBMGKAJNANIONIONCPELFAAJAFOENKGDJLGPJFKGKAANHMAHFPDFLIEKMCHCKNKPPNPBDDFHHKJADKILLEAOOIIPKNAAKAOPCNKFDNHNDAANOLJEDPAGCJIDKNFHAFAHPHMJHFICOABEHHADPDHLKAEKMDHCNCHHCBOMJAKPCNGFANAFBBBFHEDCDAEMMIJNMECDDAHCCDANNPPJJHFGGAADANPGALGAKFPJCPOMBOIKDKNDBMBIFPBNEOAADJNDANEOBKBBEKAAKGIHAGBHDNCMMBOOOGNCKMGJABEEMOJAEPICJGCDLEAMAMFHMPCHGBEELEIKKDKKMPEJJDJILAELINAANBOHOCIGDOHIHFIOOHGPMLHFDIPADPBEOICEEOCMJGIEOAGNHOAIEHCDMBAAANHDEAAEPKHMCOAGAAFHPCAILJHMICAPANCKMDABPMNIFDAMNBAACHKCCFKJHJAFAOHDAEIMPKOCOAOFOOGFAAOBDMNGGALGMKHHAFIIKHJHHGCIPAEMFPJMDJBPPNHACDANFIPGLIEFEEJAALIKMBDOEMNKDHFLHKHCHCIJIBEFPOEHMMEINJCGCEFIIAINKOHDAMOFNNAHEHFIHMHCDGEDBMNCEEECMOJACHIAMJBOHJAMAMDDAPENAACEJPEOMNHCDBAEEPPCCNACAKOBOGICEKDEFAPCDENFAGJKGNEMHHAPNMHDCHEDCOPJKJIPONONABABBIEELECBMOONIFIDKOJODJANAMDDADELIMNPMPEGMNHCDFAPMGAMNAANANHAAMGAJJIKPGMHBOHDFPIDAGEOJHANAAIOHBAANIMJNCHPCOEMMGNBGEKNOIGCFHANOEFBMAJGHNGEFDEMFJPMEIGFHMAEABMBBLMPABOHMEJNDDAAMADNAFAOPAJAACEMNCHHFDCKOGPDDHAANILMBPGODAAIANPGAKGLLJAGHPMABMOODGCDNCIBJHIHKNHHCCAMBEMPHFIBKAFHHAAFFHNFLIAHACHHOKHGJKLAECCPMFOOMGGJFNFKJIGLFOFHOGICNFDGBIAGAHCMODFBJCLKFENNOFEMMDGOJIKEDIPIDABEKKAHDKHBEHGMFDAACLLKADMKLIABNPJAOKCGHLHCOIIHOHAAKNHPCEIKGCNJOOHHMAIDPIODHAAINOPDAIIICJHAEGHCHKHCFFIMNHFKNPIDKKONDNIBNNEMEOABAAIKNCADIAPMIGAFNOHHFGIGCNGJOCOMOEPDPGBEIBEGJAICONIOANGHKIBHOGMMBPAAAMONINCOJCABANCKMDAHENGBIAIFKAFHJKABKEBJJIDCCDAAOBHCEOBMOMJCAFOOFJGFDMHOMHAPAAALDAAPCDIMOAAENEBEAAJALDHKLAILKFCMNOGFMGDEECFIHEANMNBINIBBPANMFHAAANFAPLPELIHPCIANKPECPHMELAJJACANAIKPEOOJHHHECMANHKCMDOADMNICKKPDBPIIPEMOPBENMOJAEJIECGNOGEJIEDAAMDDAPPBHDJHACNHDAOACADLACECLMOONMJIMCKBGPEAEAKFHIGIGKEFAFACKMNONAEAOJABKENNNODIKBIPGMLMOHKJOAAMFKFAIPIGADAMLFOPDAMIACOFGGOHEHMHCNAEEAHJBBIHACFANOFGCNOCAFKGCFANFKHAMAFCNJMIPKHEMFIFHLMGGGEEAMOAAMDNFINBBIFEIIFCMHBGCAEOAHJIDOABEACAMFNPKNCAHNHAAMKFBJJEFLCEAMAKCCJAHMCHCGGHCCAIKFMJDPBGKGBAFNNKCMKGECBM";
const outputCipherText = parseText(inputText);
const slogsCount = countSlogs(outputCipherText);
alert(replaceSlogs(outputCipherText));

displayObject(slogsCount);

